/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as BermudaRouteImport } from './routes/bermuda'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CobertaRouteImport } from './routes/coberta'
import { Route as EnderecoRouteImport } from './routes/endereco'
import { Route as FerramentasRouteImport } from './routes/ferramentas'
import { Route as FornoRouteImport } from './routes/forno'
import { Route as GuardaRouteImport } from './routes/guarda'
import { Route as MagnesioRouteImport } from './routes/magnesio'
import { Route as MeusPedidosRouteImport } from './routes/meus-pedidos'
import { Route as PanelaRouteImport } from './routes/panela'
import { Route as PixRouteImport } from './routes/pix'
import { Route as ShortRouteImport } from './routes/short'
import { Route as TabletRouteImport } from './routes/tablet'
import { Route as Tablet2RouteImport } from './routes/tablet2'
import { Route as TravesseiroRouteImport } from './routes/travesseiro'
import { Route as PMotoserraRouteImport } from './routes/p.motoserra'
import { Route as PMotoserraIndexRouteImport } from './routes/p.motoserra.index'
import { Route as PMotoserraAvaliacoesRouteImport } from './routes/p.motoserra.avaliacoes'
import { Route as PMotoserraCheckoutRouteImport } from './routes/p.motoserra.checkout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BermudaRoute = BermudaRouteImport.update({
  id: '/bermuda',
  path: '/bermuda',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CobertaRoute = CobertaRouteImport.update({
  id: '/coberta',
  path: '/coberta',
  getParentRoute: () => rootRouteImport,
} as any)
const EnderecoRoute = EnderecoRouteImport.update({
  id: '/endereco',
  path: '/endereco',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasRoute = FerramentasRouteImport.update({
  id: '/ferramentas',
  path: '/ferramentas',
  getParentRoute: () => rootRouteImport,
} as any)
const FornoRoute = FornoRouteImport.update({
  id: '/forno',
  path: '/forno',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardaRoute = GuardaRouteImport.update({
  id: '/guarda',
  path: '/guarda',
  getParentRoute: () => rootRouteImport,
} as any)
const MagnesioRoute = MagnesioRouteImport.update({
  id: '/magnesio',
  path: '/magnesio',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusPedidosRoute = MeusPedidosRouteImport.update({
  id: '/meus-pedidos',
  path: '/meus-pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelaRoute = PanelaRouteImport.update({
  id: '/panela',
  path: '/panela',
  getParentRoute: () => rootRouteImport,
} as any)
const PixRoute = PixRouteImport.update({
  id: '/pix',
  path: '/pix',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortRoute = ShortRouteImport.update({
  id: '/short',
  path: '/short',
  getParentRoute: () => rootRouteImport,
} as any)
const TabletRoute = TabletRouteImport.update({
  id: '/tablet',
  path: '/tablet',
  getParentRoute: () => rootRouteImport,
} as any)
const Tablet2Route = Tablet2RouteImport.update({
  id: '/tablet2',
  path: '/tablet2',
  getParentRoute: () => rootRouteImport,
} as any)
const TravesseiroRoute = TravesseiroRouteImport.update({
  id: '/travesseiro',
  path: '/travesseiro',
  getParentRoute: () => rootRouteImport,
} as any)
const PMotoserraRoute = PMotoserraRouteImport.update({
  id: '/p/motoserra',
  path: '/p/motoserra',
  getParentRoute: () => rootRouteImport,
} as any)
const PMotoserraIndexRoute = PMotoserraIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PMotoserraRoute,
} as any)
const PMotoserraAvaliacoesRoute = PMotoserraAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => PMotoserraRoute,
} as any)
const PMotoserraCheckoutRoute = PMotoserraCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => PMotoserraRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/bermuda': typeof BermudaRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/coberta': typeof CobertaRoute
  '/endereco': typeof EnderecoRoute
  '/ferramentas': typeof FerramentasRoute
  '/forno': typeof FornoRoute
  '/guarda': typeof GuardaRoute
  '/magnesio': typeof MagnesioRoute
  '/meus-pedidos': typeof MeusPedidosRoute
  '/panela': typeof PanelaRoute
  '/pix': typeof PixRoute
  '/short': typeof ShortRoute
  '/tablet': typeof TabletRoute
  '/tablet2': typeof Tablet2Route
  '/travesseiro': typeof TravesseiroRoute
  '/p/motoserra': typeof PMotoserraRouteWithChildren
  '/p/motoserra/avaliacoes': typeof PMotoserraAvaliacoesRoute
  '/p/motoserra/checkout': typeof PMotoserraCheckoutRoute
  '/p/motoserra/': typeof PMotoserraIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/bermuda': typeof BermudaRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/coberta': typeof CobertaRoute
  '/endereco': typeof EnderecoRoute
  '/ferramentas': typeof FerramentasRoute
  '/forno': typeof FornoRoute
  '/guarda': typeof GuardaRoute
  '/magnesio': typeof MagnesioRoute
  '/meus-pedidos': typeof MeusPedidosRoute
  '/panela': typeof PanelaRoute
  '/pix': typeof PixRoute
  '/short': typeof ShortRoute
  '/tablet': typeof TabletRoute
  '/tablet2': typeof Tablet2Route
  '/travesseiro': typeof TravesseiroRoute
  '/p/motoserra/avaliacoes': typeof PMotoserraAvaliacoesRoute
  '/p/motoserra/checkout': typeof PMotoserraCheckoutRoute
  '/p/motoserra': typeof PMotoserraIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/bermuda': typeof BermudaRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/coberta': typeof CobertaRoute
  '/endereco': typeof EnderecoRoute
  '/ferramentas': typeof FerramentasRoute
  '/forno': typeof FornoRoute
  '/guarda': typeof GuardaRoute
  '/magnesio': typeof MagnesioRoute
  '/meus-pedidos': typeof MeusPedidosRoute
  '/panela': typeof PanelaRoute
  '/pix': typeof PixRoute
  '/short': typeof ShortRoute
  '/tablet': typeof TabletRoute
  '/tablet2': typeof Tablet2Route
  '/travesseiro': typeof TravesseiroRoute
  '/p/motoserra': typeof PMotoserraRouteWithChildren
  '/p/motoserra/avaliacoes': typeof PMotoserraAvaliacoesRoute
  '/p/motoserra/checkout': typeof PMotoserraCheckoutRoute
  '/p/motoserra/': typeof PMotoserraIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/bermuda'
    | '/carrinho'
    | '/checkout'
    | '/coberta'
    | '/endereco'
    | '/ferramentas'
    | '/forno'
    | '/guarda'
    | '/magnesio'
    | '/meus-pedidos'
    | '/panela'
    | '/pix'
    | '/short'
    | '/tablet'
    | '/tablet2'
    | '/travesseiro'
    | '/p/motoserra'
    | '/p/motoserra/avaliacoes'
    | '/p/motoserra/checkout'
    | '/p/motoserra/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/bermuda'
    | '/carrinho'
    | '/checkout'
    | '/coberta'
    | '/endereco'
    | '/ferramentas'
    | '/forno'
    | '/guarda'
    | '/magnesio'
    | '/meus-pedidos'
    | '/panela'
    | '/pix'
    | '/short'
    | '/tablet'
    | '/tablet2'
    | '/travesseiro'
    | '/p/motoserra/avaliacoes'
    | '/p/motoserra/checkout'
    | '/p/motoserra'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/bermuda'
    | '/carrinho'
    | '/checkout'
    | '/coberta'
    | '/endereco'
    | '/ferramentas'
    | '/forno'
    | '/guarda'
    | '/magnesio'
    | '/meus-pedidos'
    | '/panela'
    | '/pix'
    | '/short'
    | '/tablet'
    | '/tablet2'
    | '/travesseiro'
    | '/p/motoserra'
    | '/p/motoserra/avaliacoes'
    | '/p/motoserra/checkout'
    | '/p/motoserra/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  BermudaRoute: typeof BermudaRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  CobertaRoute: typeof CobertaRoute
  EnderecoRoute: typeof EnderecoRoute
  FerramentasRoute: typeof FerramentasRoute
  FornoRoute: typeof FornoRoute
  GuardaRoute: typeof GuardaRoute
  MagnesioRoute: typeof MagnesioRoute
  MeusPedidosRoute: typeof MeusPedidosRoute
  PanelaRoute: typeof PanelaRoute
  PixRoute: typeof PixRoute
  ShortRoute: typeof ShortRoute
  TabletRoute: typeof TabletRoute
  Tablet2Route: typeof Tablet2Route
  TravesseiroRoute: typeof TravesseiroRoute
  PMotoserraRoute: typeof PMotoserraRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bermuda': {
      id: '/bermuda'
      path: '/bermuda'
      fullPath: '/bermuda'
      preLoaderRoute: typeof BermudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coberta': {
      id: '/coberta'
      path: '/coberta'
      fullPath: '/coberta'
      preLoaderRoute: typeof CobertaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endereco': {
      id: '/endereco'
      path: '/endereco'
      fullPath: '/endereco'
      preLoaderRoute: typeof EnderecoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas': {
      id: '/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof FerramentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forno': {
      id: '/forno'
      path: '/forno'
      fullPath: '/forno'
      preLoaderRoute: typeof FornoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guarda': {
      id: '/guarda'
      path: '/guarda'
      fullPath: '/guarda'
      preLoaderRoute: typeof GuardaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magnesio': {
      id: '/magnesio'
      path: '/magnesio'
      fullPath: '/magnesio'
      preLoaderRoute: typeof MagnesioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-pedidos': {
      id: '/meus-pedidos'
      path: '/meus-pedidos'
      fullPath: '/meus-pedidos'
      preLoaderRoute: typeof MeusPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panela': {
      id: '/panela'
      path: '/panela'
      fullPath: '/panela'
      preLoaderRoute: typeof PanelaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pix': {
      id: '/pix'
      path: '/pix'
      fullPath: '/pix'
      preLoaderRoute: typeof PixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/short': {
      id: '/short'
      path: '/short'
      fullPath: '/short'
      preLoaderRoute: typeof ShortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tablet': {
      id: '/tablet'
      path: '/tablet'
      fullPath: '/tablet'
      preLoaderRoute: typeof TabletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tablet2': {
      id: '/tablet2'
      path: '/tablet2'
      fullPath: '/tablet2'
      preLoaderRoute: typeof Tablet2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travesseiro': {
      id: '/travesseiro'
      path: '/travesseiro'
      fullPath: '/travesseiro'
      preLoaderRoute: typeof TravesseiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/motoserra': {
      id: '/p/motoserra'
      path: '/p/motoserra'
      fullPath: '/p/motoserra'
      preLoaderRoute: typeof PMotoserraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/motoserra/': {
      id: '/p/motoserra/'
      path: '/'
      fullPath: '/p/motoserra/'
      preLoaderRoute: typeof PMotoserraIndexRouteImport
      parentRoute: typeof PMotoserraRoute
    }
    '/p/motoserra/avaliacoes': {
      id: '/p/motoserra/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/p/motoserra/avaliacoes'
      preLoaderRoute: typeof PMotoserraAvaliacoesRouteImport
      parentRoute: typeof PMotoserraRoute
    }
    '/p/motoserra/checkout': {
      id: '/p/motoserra/checkout'
      path: '/checkout'
      fullPath: '/p/motoserra/checkout'
      preLoaderRoute: typeof PMotoserraCheckoutRouteImport
      parentRoute: typeof PMotoserraRoute
    }
  }
}

interface PMotoserraRouteChildren {
  PMotoserraAvaliacoesRoute: typeof PMotoserraAvaliacoesRoute
  PMotoserraCheckoutRoute: typeof PMotoserraCheckoutRoute
  PMotoserraIndexRoute: typeof PMotoserraIndexRoute
}

const PMotoserraRouteChildren: PMotoserraRouteChildren = {
  PMotoserraAvaliacoesRoute: PMotoserraAvaliacoesRoute,
  PMotoserraCheckoutRoute: PMotoserraCheckoutRoute,
  PMotoserraIndexRoute: PMotoserraIndexRoute,
}

const PMotoserraRouteWithChildren = PMotoserraRoute._addFileChildren(
  PMotoserraRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  BermudaRoute: BermudaRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  CobertaRoute: CobertaRoute,
  EnderecoRoute: EnderecoRoute,
  FerramentasRoute: FerramentasRoute,
  FornoRoute: FornoRoute,
  GuardaRoute: GuardaRoute,
  MagnesioRoute: MagnesioRoute,
  MeusPedidosRoute: MeusPedidosRoute,
  PanelaRoute: PanelaRoute,
  PixRoute: PixRoute,
  ShortRoute: ShortRoute,
  TabletRoute: TabletRoute,
  Tablet2Route: Tablet2Route,
  TravesseiroRoute: TravesseiroRoute,
  PMotoserraRoute: PMotoserraRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
